name: delivery_agent_app
description: Delivery Agent App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  #for call functionality
  # url_launcher: ^6.2.6

  # ğŸ”¥ Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.4

  # ğŸ“ Location & Maps
  geolocator: ^13.0.1
  google_maps_flutter: ^2.9.0

  # ğŸŒ Utilities
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # If you later add images/icons
  # assets:
  #   - assets/
